##The ImagePolicyWebhook configuration would be present at the remote server.
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
  - name: ImagePolicyWebhook
    configuration:
      imagePolicy:
        kubeConfigFile: path will be given in the question and would be mounted
        allowTTL: 50
        denyTTL: 50
        retryBackoff: 500
        defaultAllow: true

#After creating the admission-configuration.yml update kube-apiserver.yaml to include --admission-control-config-file which will refer the imagepolicywebhook.
#Also, include ImagePolicyWebhook in --enable-admission-plugins argument