apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev-a
  name: dev-a-role
rules:
  - apigroups: [""]
    resources: ["pods"]
    verbs: [""] 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev-b
  name: dev-b-role
rules:
  - apigroups: [""]
    resources: ["pods"]
    verbs: [""]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev-z
  name: dev-z-role
rules:
  - apigroups: [""]
    resources: ["pods"]
    verbs: ["get","list"]

---
#Rolebindings

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-a-rolebinding
  namespace: dev-a
subjects:
  - kind: User
    name: laxman
    apigroup: rbac.authorization.k8s.io/v1
roleRef:
    kind: Role
    name: dev-a-role
    apigroup: rbac.authorization.k8s.io/v1

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-b-rolebinding
  namespace: dev-b
subjects:
  - kind: User
    name: laxman
    apigroup: rbac.authorization.k8s.io/v1
roleRef:
    kind: Role
    name: dev-b-role
    apigroup: rbac.authorization.k8s.io/v1

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-z-rolebinding
  namespace: dev-z
subjects:
  - kind: User
    name: laxman
    apigroup: rbac.authorization.k8s.io/v1
roleRef:
    kind: Role
    name: dev-z-role
    apigroup: rbac.authorization.k8s.io/v1
