# RuntimeClass is defined in the node.k8s.io API group
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  # The name the RuntimeClass will be referenced by.
  # RuntimeClass is a non-namespaced resource.
  name: "name will be given in the question"
# The name of the corresponding CRI configuration
handler: runsc ( this will probably be the runtime configured in the exam)

---
#Update the runtimeClassName in pods yaml under spec section
apiVersion: v1
kind: Pod
metadata:
  name: mypod
labels:
  app: runtime
spec:
  runtimeClassName: the name of the runtime Class

#Create the pod using the above yaml 