apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-appointment-app-db
  namespace: medical-appointment-app
  labels:
    app: medapp-dp
    type: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medapp-db
  template:
    metadata:
      labels:
        app: medapp-db
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017