apiVersion: v1
kind: Namespace
metadata:
  name: medical-appointment-app
---
apiVersion: apps/v1
kind: Deployments
metadata:
  name: medical-appointment-fe
  labels:
    app: medapp-fe
    type: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medapp-fe
  template:
    spec:
      containers:
      - name: medical-appointment-fe
        image: udubey25/medical-appointment-frontend:v1
        ports:
        - containerPort: 80
      metadata:
        labels:
          app: medapp-fe