apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-appointment-app-be
  namespace: medical-appointment-app
  labels:
    app: medapp-be
    type: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medapp-be
  template:
    metadata:
      labels:
        app: medapp-be
    spec:
      containers:
      - name: medical-appointment-app-be
        image: udubey25/medical-appointment-backend:v1
        ports:
        - containerPort: 5000
        env: 
        - name: MONGO_URI 
          value: "mongodb://mongo:27017/medical-appointment-app" 
