apiVersion: v1
kind: Namespace
metadata:
  name: medical-appointment-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-appointment-app-fe
  namespace: medical-appointment-app
  labels:
    app: medapp-fe
    type: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medapp-fe
  template:
    spec:
      containers:
      - name: medical-appointment-app-fe
        image: udubey25/medical-appointment-frontend:v9.3
        ports:
        - containerPort: 80
    metadata:
      labels:
        app: medapp-fe
