apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: dev-role
rules:
- apiGroups: ["apps/v1"] # "" indicates the core API group
  resources: ["deployments"]
  verbs: ["get", "watch", "list","create"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets","pods"]
  verbs: ["get", "watch", "list","create","delete"]

---
#Creating Role Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: devns-role-binding
subjects:
#We can specify more than one subjects
- kind: User
  name: workstation
  namespace: dev
roleRef:
  kind: Role
  name: dev-role
  apiGroup: rbac.authorization.k8s.io/v1